sudo: required

language: bash

services:
  - docker

before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build

jobs:
  include:
    - stage: unit test
      script: docker-compose run --rm ci-test-app
    - stage: deploy ci
      script: docker-compose run --rm ci-deploy
    - stage: functional test
      script: docker-compose run --rm ci-test-func
    - stage: deploy production
      script: docker-compose run --rm prod-deploy
      if: tag IS present

after_success:
  - docker images
